### ISSUE TITLE
Видео перестали воспроизводиться

### ISSUE THREAD

**Issue by latatuev** [sadr0b0t/yashlang#121]
Со вчерашнего дня (03.02.2022) при воспроизведении любого видео с youtube ошибка: filed to find pattern "b=a\.get\("n"\)\)&&\(b=)(\w+)\(b\),a\.set\("n",b\)"

**Comment by sadr0b0t** [comment]
да, ютюб в очередной раз поломал доступ, уже исправлено в NewPipeExtractor 0.21.13, обновление уже в мастере, ближайшее время выпущу исправленный релиз.

**Comment by sadr0b0t** [comment]
исправлено в релизе: https://github.com/sadr0b0t/yashlang/releases/tag/v0.8.0

Подписанный apk во вложении тот же, что и в AppGallery (туда выложу чуть позже). В F-droid появится как только их билд-сервис проснется и пересоберет.

**Comment by latatuev** [comment]
Спасибо! 👍
