### ISSUE TITLE
video resolution

### ISSUE THREAD

**Issue by rinamasahiro** [sadr0b0t/yashlang#87]
Cannot control video resolution; causes interruption in video playback (buffering)

**Comment by sadr0b0t** [comment]
Implemented in release 0.8.0: https://github.com/sadr0b0t/yashlang/releases/tag/v0.8.0
more details: https://github.com/sadr0b0t/yashlang/issues/15

Signed apk is the same as in AppGallery (would publish a bit later). In F-droid would appear as soon as their build service would build and publish release (usually in few days).
